name: account_gold
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  fluttertoast: ^8.2.2
  easy_localization: ^3.0.3
  onesignal_flutter: ^3.5.1
  animated_custom_dropdown: ^1.5.0
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  flutter_typeahead: ^4.8.0
  flutter_media_downloader: ^1.0.2
  internet_connection_checker_plus: ^2.1.0


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/translations/
     - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
